// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBarUserMenu: typeof import('./components/layout/default/AppBarUserMenu.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    NavMenuGroup: typeof import('./components/layout/default/vertical-nav-menu/components/NavMenuGroup.vue')['default']
    NavMenuLink: typeof import('./components/layout/default/vertical-nav-menu/components/NavMenuLink.vue')['default']
    NavMenuSectionTitle: typeof import('./components/layout/default/vertical-nav-menu/components/NavMenuSectionTitle.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsCardVertical: typeof import('./components/statistics-card/StatisticsCardVertical.vue')['default']
    ThemeSwitcher: typeof import('./components/layout/default/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./components/UpgradeToPro.vue')['default']
    VerticalNavMenu: typeof import('./components/layout/default/vertical-nav-menu/VerticalNavMenu.vue')['default']
  }
}
